runs:
  using: composite
  steps:
    - uses: actualbudget/actions/setup@main
    - name: Check release notes
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      shell: bash
      run: node actions/release-notes/check/index.js
